### ISSUE TITLE
get_initial_map 2d array dimensions should be switched

### ISSUE THREAD

**Issue by Paul-Andre** [naumazeredo/battlecode-2018-cpp-api#8]
https://github.com/naumazeredo/battlecode-2018-cpp-api/blob/c5133b4b1da56648b2c50ce7dbb71f3470c4f9d6/bc.hpp#L767-L780

When doing `MapLocation mp{m_planet, i, j};`, i becomes the x coordinate and j becomes the y coordinate. But otherwise, i<height and j<width throughout all the function. Either i and j should be switched in the MapLocation or width and height should be switched throughout the function. I personally prefer switching width and height and having `array[x][y]` as the convention.

**Comment by naumazeredo** [comment]
Thanks!
